---
- name: "{{ iptables_state__task_name | d('iptables_state') }}"
  iptables_state:
    path:       "{{ iptables_state__path }}"
    state:      "{{ iptables_state__state }}"
    table:      "{{ iptables_state__table      | d(omit) }}"
    wait:       "{{ iptables_state__wait       | d(omit) }}"
    noflush:    "{{ iptables_state__noflush    | d(omit) }}"
    counters:   "{{ iptables_state__counters   | d(omit) }}"
    modprobe:   "{{ iptables_state__modprobe   | d(omit) }}"
    ip_version: "{{ iptables_state__ip_version | d(omit) }}"
  #throttle: 1
  async: "{{ (iptables_state__state | d() == 'restored') | ternary(ansible_timeout, omit) }}"
  poll:  "{{ (iptables_state__state | d() == 'restored') | ternary(0, omit) }}"
  register: iptables_state__registered
...
